name: Issue Notification

permissions:
  issues: write
  contents: read

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Send automatic comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          **Nouvelle Issue Signalée !**

          Merci @${{ github.event.issue.user.login }} d'avoir signalé ce problème.

          Tous les collaborateurs sont invités à prendre connaissance de cette issue.

          👉 Priorité : à examiner  
          👉 Statut : en attente de triage

          _Ceci est un message automatique._
